import { CommandService } from './../../services/command.service';
import { ClientService } from './../../services/client.service';
import { Component, OnInit } from '@angular/core';
declare let jsPDF;
import { Cookie } from 'ng2-cookies/ng2-cookies';

@Component({
  selector: 'app-credit-number',
  templateUrl: './credit-number.component.html',
  styleUrls: ['./credit-number.component.css'],
  providers: [CommandService, ClientService]
})
export class CreditNumberComponent implements OnInit {

  client = {
    firstName: "",
    lastName: "",
    address: ""
  }
  constructor(private commandService: CommandService, private clientService: ClientService) { }

  ngOnInit() {
  }

  generateDoc(client): void {
    //client.commands=+Cookie.get('angular-command')
    console.log(client)
    this.clientService.addClient(client)
      .subscribe(data => {
        console.log(data)
      })

    let total = 0
    let nb
    let id = Cookie.get('angular-command')
    this.commandService
      .getCommandById(+Cookie.get('angular-command'))
      .subscribe(data => {
        console.log(data)
        // to be managed
        var doc = new jsPDF();
        doc.text(20, 10, `Bill N° ${id}
        Bill's date ${data.date}`);
        nb = data.books.length

        doc.text(20, 50, `Books`);
        doc.text(80, 50, `Quantity`);
        doc.text(140, 50, `Price Per Unit `);
        doc.text(180, 50, ` Price`);
        data.books.forEach((element, key) => {
          doc.text(20, 70 + (key * 20), `${element.name}`)
          doc.text(80, 70 + (key * 20), `${element.TotalQty} `)
          doc.text(140, 70 + (key * 20), `${element.oldPrice}`)
          doc.text(180, 70 + (key * 20), `${element.oldPrice * element.TotalQty}`)
          //        doc.addImage(element.img, 'JPEG', 15, 40, 180, 160)
          total += element.oldPrice * element.TotalQty
        });

        doc.text(100, 70 + (nb * 20), ` Total Price ${total} `);

        doc.text(20, 90 + (nb * 20), ` Client's name: ${client.firstName}  ${client.lastName} `)
        doc.text(20, 110 + (nb * 20), ` Client's address: ${client.address} `)
        doc.text(20, 220, 'Generated By jeBouqine');
        // Save the PDF
        doc.setFont("helvetica");
        doc.setFontType("bold");
        doc.setFontSize(9);
        doc.save('Bill.pdf');
      })
    Cookie.delete('angular-command')
  }

}