import { CommandService } from './../../services/command.service';
import { Component, OnInit } from '@angular/core';
declare let jsPDF;
import { Cookie } from 'ng2-cookies/ng2-cookies';

@Component({
  selector: 'app-credit-number',
  templateUrl: './credit-number.component.html',
  styleUrls: ['./credit-number.component.css'],
  providers: [CommandService]
})
export class CreditNumberComponent implements OnInit {

  constructor(private commandService: CommandService) { }

  ngOnInit() {
  }

  generateDoc(): void{
    this.commandService
    .getCommandById(+Cookie.get('angular-command'))
    .subscribe(data => {
        console.log(data)
        // to be managed
        var doc = new jsPDF();
        doc.text(20, 20, `Bill N° ${data._id}
        Bill's date ${data.date}`);
        data.books.forEach((element, key) => {
          doc.text(20, 30 + (key * 10), `Books: ${element.name}`)
          doc.text(30, 30 + (key * 20),`${element.TotalQty}`)
          doc.text(40, 30 + (key * 30),`${element.oldPrice}`)
          //        doc.addImage(element.img, 'JPEG', 15, 40, 180, 160)

        });
        doc.addPage();
        doc.text(20, 100, 'Generated By jeBouqine');
        // Save the PDF
        doc.save('Test.pdf');
    })
  }
  
}
